// Code generated by protoc-gen-go. DO NOT EDIT.
// source: medifor/v1/provenance.proto

package mediforproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LinkType int32

const (
	LinkType_SPLICE     LinkType = 0
	LinkType_PROVENANCE LinkType = 1
	LinkType_SPEAKER    LinkType = 2
	LinkType_CAMERA     LinkType = 3
	LinkType_LOCATION   LinkType = 4
)

var LinkType_name = map[int32]string{
	0: "SPLICE",
	1: "PROVENANCE",
	2: "SPEAKER",
	3: "CAMERA",
	4: "LOCATION",
}

var LinkType_value = map[string]int32{
	"SPLICE":     0,
	"PROVENANCE": 1,
	"SPEAKER":    2,
	"CAMERA":     3,
	"LOCATION":   4,
}

func (x LinkType) String() string {
	return proto.EnumName(LinkType_name, int32(x))
}

func (LinkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{0}
}

// FilterRequest is used to ask a provenance analytic to return the
// top N matches for a given image.
type ProvenanceFilteringRequest struct {
	// Unique identifier for the request.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The image to be sent to the provenance analytic.
	Image *Resource `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// The number of results to return
	ResultLimit          int32    `protobuf:"varint,3,opt,name=result_limit,json=resultLimit,proto3" json:"result_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvenanceFilteringRequest) Reset()         { *m = ProvenanceFilteringRequest{} }
func (m *ProvenanceFilteringRequest) String() string { return proto.CompactTextString(m) }
func (*ProvenanceFilteringRequest) ProtoMessage()    {}
func (*ProvenanceFilteringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{0}
}

func (m *ProvenanceFilteringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvenanceFilteringRequest.Unmarshal(m, b)
}
func (m *ProvenanceFilteringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvenanceFilteringRequest.Marshal(b, m, deterministic)
}
func (m *ProvenanceFilteringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvenanceFilteringRequest.Merge(m, src)
}
func (m *ProvenanceFilteringRequest) XXX_Size() int {
	return xxx_messageInfo_ProvenanceFilteringRequest.Size(m)
}
func (m *ProvenanceFilteringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvenanceFilteringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvenanceFilteringRequest proto.InternalMessageInfo

func (m *ProvenanceFilteringRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ProvenanceFilteringRequest) GetImage() *Resource {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ProvenanceFilteringRequest) GetResultLimit() int32 {
	if m != nil {
		return m.ResultLimit
	}
	return 0
}

// ImageMatch contains the image identifier and score denoting how
// closely it matches the probe image.
type ImageMatch struct {
	// Unique identifier for the image.
	ImageId string `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// The image resource.
	MatchingImage *Resource `protobuf:"bytes,2,opt,name=matching_image,json=matchingImage,proto3" json:"matching_image,omitempty"`
	// The score for the matching image.
	Score                float32  `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageMatch) Reset()         { *m = ImageMatch{} }
func (m *ImageMatch) String() string { return proto.CompactTextString(m) }
func (*ImageMatch) ProtoMessage()    {}
func (*ImageMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{1}
}

func (m *ImageMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageMatch.Unmarshal(m, b)
}
func (m *ImageMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageMatch.Marshal(b, m, deterministic)
}
func (m *ImageMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageMatch.Merge(m, src)
}
func (m *ImageMatch) XXX_Size() int {
	return xxx_messageInfo_ImageMatch.Size(m)
}
func (m *ImageMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageMatch.DiscardUnknown(m)
}

var xxx_messageInfo_ImageMatch proto.InternalMessageInfo

func (m *ImageMatch) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *ImageMatch) GetMatchingImage() *Resource {
	if m != nil {
		return m.MatchingImage
	}
	return nil
}

func (m *ImageMatch) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// ImageFilter contains the top N results that match the probe image
// along with the corresponding scores.
type FilteringResult struct {
	// List of matching images with scores.  The length of the list
	// is determined by the result_limit provided in the request.
	Matches []*ImageMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	// Probe image sent for the filter request, reference (Optional)/
	Probe                *Resource `protobuf:"bytes,2,opt,name=probe,proto3" json:"probe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FilteringResult) Reset()         { *m = FilteringResult{} }
func (m *FilteringResult) String() string { return proto.CompactTextString(m) }
func (*FilteringResult) ProtoMessage()    {}
func (*FilteringResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{2}
}

func (m *FilteringResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilteringResult.Unmarshal(m, b)
}
func (m *FilteringResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilteringResult.Marshal(b, m, deterministic)
}
func (m *FilteringResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilteringResult.Merge(m, src)
}
func (m *FilteringResult) XXX_Size() int {
	return xxx_messageInfo_FilteringResult.Size(m)
}
func (m *FilteringResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FilteringResult.DiscardUnknown(m)
}

var xxx_messageInfo_FilteringResult proto.InternalMessageInfo

func (m *FilteringResult) GetMatches() []*ImageMatch {
	if m != nil {
		return m.Matches
	}
	return nil
}

func (m *FilteringResult) GetProbe() *Resource {
	if m != nil {
		return m.Probe
	}
	return nil
}

// ProvenanceGraphRequest provides a provenance analytic with a probe image
// and the results of the filtering task to the analytic.
type ProvenanceGraphRequest struct {
	// Unique identifier for the request.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The image to be sent to the provenance analytic.
	Image *Resource `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Image matches from the provenance filtering task
	FilterResults        []*ImageMatch `protobuf:"bytes,3,rep,name=filter_results,json=filterResults,proto3" json:"filter_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProvenanceGraphRequest) Reset()         { *m = ProvenanceGraphRequest{} }
func (m *ProvenanceGraphRequest) String() string { return proto.CompactTextString(m) }
func (*ProvenanceGraphRequest) ProtoMessage()    {}
func (*ProvenanceGraphRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{3}
}

func (m *ProvenanceGraphRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvenanceGraphRequest.Unmarshal(m, b)
}
func (m *ProvenanceGraphRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvenanceGraphRequest.Marshal(b, m, deterministic)
}
func (m *ProvenanceGraphRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvenanceGraphRequest.Merge(m, src)
}
func (m *ProvenanceGraphRequest) XXX_Size() int {
	return xxx_messageInfo_ProvenanceGraphRequest.Size(m)
}
func (m *ProvenanceGraphRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvenanceGraphRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvenanceGraphRequest proto.InternalMessageInfo

func (m *ProvenanceGraphRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ProvenanceGraphRequest) GetImage() *Resource {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ProvenanceGraphRequest) GetFilterResults() []*ImageMatch {
	if m != nil {
		return m.FilterResults
	}
	return nil
}

// Association provides details describing the relationship between two probes.
type Association struct {
	// The specific tyle of link created
	Type LinkType `protobuf:"varint,1,opt,name=type,proto3,enum=mediforproto.LinkType" json:"type,omitempty"`
	// UUID of the probe image
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// UUID of the matching image
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// Real number that is higher if the association exists.
	Score float32 `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	// Explanation of the association and supporting evidence.
	Explanation          string   `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Association) Reset()         { *m = Association{} }
func (m *Association) String() string { return proto.CompactTextString(m) }
func (*Association) ProtoMessage()    {}
func (*Association) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{4}
}

func (m *Association) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Association.Unmarshal(m, b)
}
func (m *Association) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Association.Marshal(b, m, deterministic)
}
func (m *Association) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Association.Merge(m, src)
}
func (m *Association) XXX_Size() int {
	return xxx_messageInfo_Association.Size(m)
}
func (m *Association) XXX_DiscardUnknown() {
	xxx_messageInfo_Association.DiscardUnknown(m)
}

var xxx_messageInfo_Association proto.InternalMessageInfo

func (m *Association) GetType() LinkType {
	if m != nil {
		return m.Type
	}
	return LinkType_SPLICE
}

func (m *Association) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Association) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Association) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Association) GetExplanation() string {
	if m != nil {
		return m.Explanation
	}
	return ""
}

// Association provides details describing the relationship between two probes.
type Node struct {
	// UUID of the image
	ImageId string `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// Real number that is higher if an image is in the graph
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{5}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Node) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// ProvenanceGraph
type ProvenanceGraph struct {
	// List of nodes in the graph.
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// List of associations that specify the relationship between nodes on the gra
	Associations []*Association `protobuf:"bytes,2,rep,name=associations,proto3" json:"associations,omitempty"`
	// Whether the algorithm opted out of the task
	OptOut               bool     `protobuf:"varint,3,opt,name=opt_out,json=optOut,proto3" json:"opt_out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvenanceGraph) Reset()         { *m = ProvenanceGraph{} }
func (m *ProvenanceGraph) String() string { return proto.CompactTextString(m) }
func (*ProvenanceGraph) ProtoMessage()    {}
func (*ProvenanceGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2b3056807758b, []int{6}
}

func (m *ProvenanceGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvenanceGraph.Unmarshal(m, b)
}
func (m *ProvenanceGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvenanceGraph.Marshal(b, m, deterministic)
}
func (m *ProvenanceGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvenanceGraph.Merge(m, src)
}
func (m *ProvenanceGraph) XXX_Size() int {
	return xxx_messageInfo_ProvenanceGraph.Size(m)
}
func (m *ProvenanceGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvenanceGraph.DiscardUnknown(m)
}

var xxx_messageInfo_ProvenanceGraph proto.InternalMessageInfo

func (m *ProvenanceGraph) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ProvenanceGraph) GetAssociations() []*Association {
	if m != nil {
		return m.Associations
	}
	return nil
}

func (m *ProvenanceGraph) GetOptOut() bool {
	if m != nil {
		return m.OptOut
	}
	return false
}

func init() {
	proto.RegisterEnum("mediforproto.LinkType", LinkType_name, LinkType_value)
	proto.RegisterType((*ProvenanceFilteringRequest)(nil), "mediforproto.ProvenanceFilteringRequest")
	proto.RegisterType((*ImageMatch)(nil), "mediforproto.ImageMatch")
	proto.RegisterType((*FilteringResult)(nil), "mediforproto.FilteringResult")
	proto.RegisterType((*ProvenanceGraphRequest)(nil), "mediforproto.ProvenanceGraphRequest")
	proto.RegisterType((*Association)(nil), "mediforproto.Association")
	proto.RegisterType((*Node)(nil), "mediforproto.Node")
	proto.RegisterType((*ProvenanceGraph)(nil), "mediforproto.ProvenanceGraph")
}

func init() { proto.RegisterFile("medifor/v1/provenance.proto", fileDescriptor_77e2b3056807758b) }

var fileDescriptor_77e2b3056807758b = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x9c, 0xff, 0xdc, 0xa4, 0x69, 0x34, 0x1f, 0x6a, 0xdd, 0xa2, 0x4a, 0x21, 0x62, 0x11,
	0x55, 0x28, 0x11, 0x61, 0xc1, 0xaa, 0x42, 0x69, 0x14, 0x50, 0x44, 0x9a, 0x44, 0xd3, 0x8a, 0x05,
	0x8b, 0x46, 0x53, 0x7b, 0xea, 0x8e, 0x1a, 0x7b, 0xcc, 0xcc, 0xb8, 0xa2, 0x12, 0x8f, 0xc0, 0x8e,
	0x27, 0x60, 0xc3, 0xd3, 0xf0, 0x50, 0xc8, 0x33, 0xf9, 0xb1, 0x2d, 0x4a, 0xd9, 0xb0, 0x4a, 0xee,
	0xf5, 0xb9, 0xf7, 0x9c, 0x7b, 0xee, 0xcc, 0xc0, 0x53, 0x9f, 0xba, 0xec, 0x9a, 0x8b, 0xde, 0xdd,
	0xcb, 0x5e, 0x28, 0xf8, 0x1d, 0x0d, 0x48, 0xe0, 0xd0, 0x6e, 0x28, 0xb8, 0xe2, 0xa8, 0xbe, 0xfa,
	0xa8, 0xa3, 0xc3, 0x83, 0x04, 0x94, 0x04, 0x64, 0x79, 0xaf, 0x98, 0x63, 0x80, 0xed, 0xaf, 0x16,
	0x1c, 0xce, 0x37, 0xd5, 0x6f, 0xd9, 0x52, 0x51, 0xc1, 0x02, 0x0f, 0xd3, 0x4f, 0x11, 0x95, 0x0a,
	0x1d, 0x01, 0x08, 0xf3, 0x77, 0xc1, 0x5c, 0xdb, 0x6a, 0x59, 0x9d, 0x2a, 0xae, 0xae, 0x32, 0x63,
	0x17, 0xbd, 0x80, 0x22, 0xf3, 0x89, 0x47, 0xed, 0x5c, 0xcb, 0xea, 0xd4, 0xfa, 0x7b, 0xdd, 0x24,
	0x6d, 0x17, 0x53, 0xc9, 0x23, 0xe1, 0x50, 0x6c, 0x40, 0xe8, 0x19, 0xd4, 0x05, 0x95, 0xd1, 0x52,
	0x2d, 0x96, 0xcc, 0x67, 0xca, 0xce, 0xb7, 0xac, 0x4e, 0x11, 0xd7, 0x4c, 0x6e, 0x12, 0xa7, 0xda,
	0x5f, 0x00, 0xc6, 0x31, 0xf6, 0x8c, 0x28, 0xe7, 0x06, 0x1d, 0x40, 0x45, 0x57, 0x6e, 0xb9, 0xcb,
	0x3a, 0x1e, 0xbb, 0xe8, 0x04, 0x1a, 0x7e, 0x8c, 0x61, 0x81, 0xb7, 0xf8, 0x1b, 0x09, 0x3b, 0x6b,
	0xb4, 0x6e, 0x8f, 0x9e, 0x40, 0x51, 0x3a, 0x5c, 0x50, 0xad, 0x21, 0x87, 0x4d, 0xd0, 0x96, 0xb0,
	0x9b, 0x70, 0x20, 0x56, 0x85, 0xfa, 0x50, 0xd6, 0x95, 0x54, 0xda, 0x56, 0x2b, 0xdf, 0xa9, 0xf5,
	0xed, 0x34, 0xc1, 0x56, 0x2d, 0x5e, 0x03, 0x63, 0x57, 0x42, 0xc1, 0xaf, 0x1e, 0x75, 0x45, 0x83,
	0xda, 0x3f, 0x2c, 0xd8, 0xdb, 0x6e, 0xe0, 0x9d, 0x20, 0xe1, 0xcd, 0x3f, 0x71, 0xff, 0x0d, 0x34,
	0xae, 0xf5, 0x70, 0x0b, 0x63, 0xb8, 0xb4, 0xf3, 0x8f, 0x0c, 0xb4, 0x63, 0xf0, 0xc6, 0x09, 0xd9,
	0xfe, 0x6e, 0x41, 0x6d, 0x20, 0x25, 0x77, 0x18, 0x51, 0x8c, 0x07, 0xe8, 0x18, 0x0a, 0xea, 0x3e,
	0xa4, 0x5a, 0x57, 0x23, 0xcb, 0x3e, 0x61, 0xc1, 0xed, 0xc5, 0x7d, 0x48, 0xb1, 0xc6, 0xa0, 0x3d,
	0x28, 0x19, 0x35, 0x5a, 0x6b, 0x15, 0xaf, 0xa2, 0x38, 0xaf, 0x88, 0xf0, 0xa8, 0x39, 0x0c, 0x55,
	0xbc, 0x8a, 0xb6, 0xfb, 0x29, 0x24, 0xf6, 0x83, 0x5a, 0x50, 0xa3, 0x9f, 0xc3, 0x25, 0x09, 0xb4,
	0x00, 0xbb, 0xa8, 0x4b, 0x92, 0xa9, 0xf6, 0x6b, 0x28, 0x4c, 0xb9, 0x4b, 0xff, 0x74, 0x72, 0x36,
	0xad, 0x73, 0xc9, 0xd5, 0x7f, 0xb3, 0x60, 0x37, 0xb3, 0x05, 0xd4, 0x81, 0x62, 0xc0, 0xdd, 0xcd,
	0xe6, 0x51, 0x7a, 0xc2, 0x98, 0x07, 0x1b, 0x00, 0x3a, 0x81, 0x3a, 0xd9, 0x3a, 0x23, 0xed, 0x9c,
	0x2e, 0x38, 0x48, 0x17, 0x24, 0xbc, 0xc3, 0x29, 0x38, 0xda, 0x87, 0x32, 0x0f, 0xd5, 0x82, 0x47,
	0xc6, 0x86, 0x0a, 0x2e, 0xf1, 0x50, 0xcd, 0x22, 0x75, 0x7c, 0x06, 0x95, 0xb5, 0x91, 0x08, 0xa0,
	0x74, 0x3e, 0x9f, 0x8c, 0x87, 0xa3, 0xe6, 0x7f, 0xa8, 0x01, 0x30, 0xc7, 0xb3, 0x0f, 0xa3, 0xe9,
	0x60, 0x3a, 0x1c, 0x35, 0x2d, 0x54, 0x83, 0xf2, 0xf9, 0x7c, 0x34, 0x78, 0x3f, 0xc2, 0xcd, 0x5c,
	0x0c, 0x1c, 0x0e, 0xce, 0x46, 0x78, 0xd0, 0xcc, 0xa3, 0x3a, 0x54, 0x26, 0xb3, 0xe1, 0xe0, 0x62,
	0x3c, 0x9b, 0x36, 0x0b, 0xfd, 0x9f, 0x16, 0xc0, 0x76, 0x48, 0x74, 0x09, 0xff, 0xff, 0xe6, 0xea,
	0xa3, 0x4e, 0x5a, 0xf6, 0xc3, 0xaf, 0xc3, 0xe1, 0x51, 0x1a, 0x99, 0xbd, 0x3b, 0x97, 0xb0, 0x9f,
	0xb1, 0xf4, 0x34, 0x62, 0x4b, 0x37, 0xe6, 0x78, 0xfe, 0x10, 0x47, 0xf2, 0xfc, 0x67, 0xfb, 0x67,
	0x9b, 0x2d, 0xc0, 0x76, 0xb8, 0x9f, 0xc0, 0x78, 0x82, 0xf8, 0xe6, 0x5d, 0x3b, 0x4d, 0x2c, 0x73,
	0x1e, 0x27, 0x3e, 0xf6, 0x3d, 0xa6, 0x6e, 0xa2, 0xab, 0xae, 0xc3, 0xfd, 0x5e, 0x5c, 0x41, 0xae,
	0xb9, 0xa0, 0x81, 0x64, 0x8e, 0xec, 0xad, 0x5f, 0xc7, 0xf0, 0xd6, 0xeb, 0x25, 0x09, 0xaf, 0x4a,
	0xfa, 0xe7, 0xd5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xf4, 0xcb, 0xd8, 0x6b, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvenanceClient is the client API for Provenance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvenanceClient interface {
	ProvenanceFiltering(ctx context.Context, in *ProvenanceFilteringRequest, opts ...grpc.CallOption) (*FilteringResult, error)
	ProvenanceGraphBuilding(ctx context.Context, in *ProvenanceGraphRequest, opts ...grpc.CallOption) (*ProvenanceGraph, error)
}

type provenanceClient struct {
	cc *grpc.ClientConn
}

func NewProvenanceClient(cc *grpc.ClientConn) ProvenanceClient {
	return &provenanceClient{cc}
}

func (c *provenanceClient) ProvenanceFiltering(ctx context.Context, in *ProvenanceFilteringRequest, opts ...grpc.CallOption) (*FilteringResult, error) {
	out := new(FilteringResult)
	err := c.cc.Invoke(ctx, "/mediforproto.Provenance/ProvenanceFiltering", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provenanceClient) ProvenanceGraphBuilding(ctx context.Context, in *ProvenanceGraphRequest, opts ...grpc.CallOption) (*ProvenanceGraph, error) {
	out := new(ProvenanceGraph)
	err := c.cc.Invoke(ctx, "/mediforproto.Provenance/ProvenanceGraphBuilding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvenanceServer is the server API for Provenance service.
type ProvenanceServer interface {
	ProvenanceFiltering(context.Context, *ProvenanceFilteringRequest) (*FilteringResult, error)
	ProvenanceGraphBuilding(context.Context, *ProvenanceGraphRequest) (*ProvenanceGraph, error)
}

// UnimplementedProvenanceServer can be embedded to have forward compatible implementations.
type UnimplementedProvenanceServer struct {
}

func (*UnimplementedProvenanceServer) ProvenanceFiltering(ctx context.Context, req *ProvenanceFilteringRequest) (*FilteringResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvenanceFiltering not implemented")
}
func (*UnimplementedProvenanceServer) ProvenanceGraphBuilding(ctx context.Context, req *ProvenanceGraphRequest) (*ProvenanceGraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvenanceGraphBuilding not implemented")
}

func RegisterProvenanceServer(s *grpc.Server, srv ProvenanceServer) {
	s.RegisterService(&_Provenance_serviceDesc, srv)
}

func _Provenance_ProvenanceFiltering_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvenanceFilteringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceServer).ProvenanceFiltering(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mediforproto.Provenance/ProvenanceFiltering",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceServer).ProvenanceFiltering(ctx, req.(*ProvenanceFilteringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provenance_ProvenanceGraphBuilding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvenanceGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvenanceServer).ProvenanceGraphBuilding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mediforproto.Provenance/ProvenanceGraphBuilding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvenanceServer).ProvenanceGraphBuilding(ctx, req.(*ProvenanceGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provenance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mediforproto.Provenance",
	HandlerType: (*ProvenanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvenanceFiltering",
			Handler:    _Provenance_ProvenanceFiltering_Handler,
		},
		{
			MethodName: "ProvenanceGraphBuilding",
			Handler:    _Provenance_ProvenanceGraphBuilding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "medifor/v1/provenance.proto",
}
