# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from medifor.v1 import analytic_pb2 as medifor_dot_v1_dot_analytic__pb2
from medifor.v1 import fusion_pb2 as medifor_dot_v1_dot_fusion__pb2


class FuserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FuseImageManipulation = channel.unary_unary(
                '/mediforproto.Fuser/FuseImageManipulation',
                request_serializer=medifor_dot_v1_dot_fusion__pb2.FuseImageManipulationRequest.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_analytic__pb2.ImageManipulation.FromString,
                )
        self.FuseImageSplice = channel.unary_unary(
                '/mediforproto.Fuser/FuseImageSplice',
                request_serializer=medifor_dot_v1_dot_fusion__pb2.FuseImageSpliceRequest.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_analytic__pb2.ImageSplice.FromString,
                )
        self.FuseVideoManipulation = channel.unary_unary(
                '/mediforproto.Fuser/FuseVideoManipulation',
                request_serializer=medifor_dot_v1_dot_fusion__pb2.FuseVideoManipulationRequest.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_analytic__pb2.VideoManipulation.FromString,
                )
        self.FuseImageCameraMatch = channel.unary_unary(
                '/mediforproto.Fuser/FuseImageCameraMatch',
                request_serializer=medifor_dot_v1_dot_fusion__pb2.FuseImageCameraMatchRequest.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_analytic__pb2.ImageCameraMatch.FromString,
                )
        self.FuseVideoCameraMatch = channel.unary_unary(
                '/mediforproto.Fuser/FuseVideoCameraMatch',
                request_serializer=medifor_dot_v1_dot_fusion__pb2.FuseVideoCameraMatchRequest.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_analytic__pb2.VideoCameraMatch.FromString,
                )
        self.Kill = channel.unary_unary(
                '/mediforproto.Fuser/Kill',
                request_serializer=medifor_dot_v1_dot_analytic__pb2.Empty.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_analytic__pb2.Empty.FromString,
                )


class FuserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FuseImageManipulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuseImageSplice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuseVideoManipulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuseImageCameraMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuseVideoCameraMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FuserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FuseImageManipulation': grpc.unary_unary_rpc_method_handler(
                    servicer.FuseImageManipulation,
                    request_deserializer=medifor_dot_v1_dot_fusion__pb2.FuseImageManipulationRequest.FromString,
                    response_serializer=medifor_dot_v1_dot_analytic__pb2.ImageManipulation.SerializeToString,
            ),
            'FuseImageSplice': grpc.unary_unary_rpc_method_handler(
                    servicer.FuseImageSplice,
                    request_deserializer=medifor_dot_v1_dot_fusion__pb2.FuseImageSpliceRequest.FromString,
                    response_serializer=medifor_dot_v1_dot_analytic__pb2.ImageSplice.SerializeToString,
            ),
            'FuseVideoManipulation': grpc.unary_unary_rpc_method_handler(
                    servicer.FuseVideoManipulation,
                    request_deserializer=medifor_dot_v1_dot_fusion__pb2.FuseVideoManipulationRequest.FromString,
                    response_serializer=medifor_dot_v1_dot_analytic__pb2.VideoManipulation.SerializeToString,
            ),
            'FuseImageCameraMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FuseImageCameraMatch,
                    request_deserializer=medifor_dot_v1_dot_fusion__pb2.FuseImageCameraMatchRequest.FromString,
                    response_serializer=medifor_dot_v1_dot_analytic__pb2.ImageCameraMatch.SerializeToString,
            ),
            'FuseVideoCameraMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FuseVideoCameraMatch,
                    request_deserializer=medifor_dot_v1_dot_fusion__pb2.FuseVideoCameraMatchRequest.FromString,
                    response_serializer=medifor_dot_v1_dot_analytic__pb2.VideoCameraMatch.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=medifor_dot_v1_dot_analytic__pb2.Empty.FromString,
                    response_serializer=medifor_dot_v1_dot_analytic__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mediforproto.Fuser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fuser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FuseImageManipulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Fuser/FuseImageManipulation',
            medifor_dot_v1_dot_fusion__pb2.FuseImageManipulationRequest.SerializeToString,
            medifor_dot_v1_dot_analytic__pb2.ImageManipulation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FuseImageSplice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Fuser/FuseImageSplice',
            medifor_dot_v1_dot_fusion__pb2.FuseImageSpliceRequest.SerializeToString,
            medifor_dot_v1_dot_analytic__pb2.ImageSplice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FuseVideoManipulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Fuser/FuseVideoManipulation',
            medifor_dot_v1_dot_fusion__pb2.FuseVideoManipulationRequest.SerializeToString,
            medifor_dot_v1_dot_analytic__pb2.VideoManipulation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FuseImageCameraMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Fuser/FuseImageCameraMatch',
            medifor_dot_v1_dot_fusion__pb2.FuseImageCameraMatchRequest.SerializeToString,
            medifor_dot_v1_dot_analytic__pb2.ImageCameraMatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FuseVideoCameraMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Fuser/FuseVideoCameraMatch',
            medifor_dot_v1_dot_fusion__pb2.FuseVideoCameraMatchRequest.SerializeToString,
            medifor_dot_v1_dot_analytic__pb2.VideoCameraMatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Fuser/Kill',
            medifor_dot_v1_dot_analytic__pb2.Empty.SerializeToString,
            medifor_dot_v1_dot_analytic__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
