# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medifor/v1/kill.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from medifor.v1 import analytic_pb2 as medifor_dot_v1_dot_analytic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='medifor/v1/kill.proto',
  package='mediforproto',
  syntax='proto3',
  serialized_options=_b('\n\030com.mediforprogram.protoB\tKillProto'),
  serialized_pb=_b('\n\x15medifor/v1/kill.proto\x12\x0cmediforproto\x1a\x19medifor/v1/analytic.proto2<\n\x08Killable\x12\x30\n\x04Kill\x12\x13.mediforproto.Empty\x1a\x13.mediforproto.EmptyB%\n\x18\x63om.mediforprogram.protoB\tKillProtob\x06proto3')
  ,
  dependencies=[medifor_dot_v1_dot_analytic__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_KILLABLE = _descriptor.ServiceDescriptor(
  name='Killable',
  full_name='mediforproto.Killable',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=66,
  serialized_end=126,
  methods=[
  _descriptor.MethodDescriptor(
    name='Kill',
    full_name='mediforproto.Killable.Kill',
    index=0,
    containing_service=None,
    input_type=medifor_dot_v1_dot_analytic__pb2._EMPTY,
    output_type=medifor_dot_v1_dot_analytic__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KILLABLE)

DESCRIPTOR.services_by_name['Killable'] = _KILLABLE

# @@protoc_insertion_point(module_scope)
