# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from medifor.v1 import analytic_pb2 as medifor_dot_v1_dot_analytic__pb2


class KillableStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Kill = channel.unary_unary(
        '/mediforproto.Killable/Kill',
        request_serializer=medifor_dot_v1_dot_analytic__pb2.Empty.SerializeToString,
        response_deserializer=medifor_dot_v1_dot_analytic__pb2.Empty.FromString,
        )


class KillableServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Kill(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KillableServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Kill': grpc.unary_unary_rpc_method_handler(
          servicer.Kill,
          request_deserializer=medifor_dot_v1_dot_analytic__pb2.Empty.FromString,
          response_serializer=medifor_dot_v1_dot_analytic__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mediforproto.Killable', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
