# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from medifor.v1 import provenance_pb2 as medifor_dot_v1_dot_provenance__pb2


class ProvenanceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProvenanceFiltering = channel.unary_unary(
                '/mediforproto.Provenance/ProvenanceFiltering',
                request_serializer=medifor_dot_v1_dot_provenance__pb2.ProvenanceFilteringRequest.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_provenance__pb2.FilteringResult.FromString,
                )
        self.ProvenanceGraphBuilding = channel.unary_unary(
                '/mediforproto.Provenance/ProvenanceGraphBuilding',
                request_serializer=medifor_dot_v1_dot_provenance__pb2.ProvenanceGraphRequest.SerializeToString,
                response_deserializer=medifor_dot_v1_dot_provenance__pb2.ProvenanceGraph.FromString,
                )


class ProvenanceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProvenanceFiltering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvenanceGraphBuilding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProvenanceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProvenanceFiltering': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvenanceFiltering,
                    request_deserializer=medifor_dot_v1_dot_provenance__pb2.ProvenanceFilteringRequest.FromString,
                    response_serializer=medifor_dot_v1_dot_provenance__pb2.FilteringResult.SerializeToString,
            ),
            'ProvenanceGraphBuilding': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvenanceGraphBuilding,
                    request_deserializer=medifor_dot_v1_dot_provenance__pb2.ProvenanceGraphRequest.FromString,
                    response_serializer=medifor_dot_v1_dot_provenance__pb2.ProvenanceGraph.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mediforproto.Provenance', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Provenance(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProvenanceFiltering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Provenance/ProvenanceFiltering',
            medifor_dot_v1_dot_provenance__pb2.ProvenanceFilteringRequest.SerializeToString,
            medifor_dot_v1_dot_provenance__pb2.FilteringResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProvenanceGraphBuilding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mediforproto.Provenance/ProvenanceGraphBuilding',
            medifor_dot_v1_dot_provenance__pb2.ProvenanceGraphRequest.SerializeToString,
            medifor_dot_v1_dot_provenance__pb2.ProvenanceGraph.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
