# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from medifor.v1 import streamingproxy_pb2 as medifor_dot_v1_dot_streamingproxy__pb2


class StreamingProxyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DetectStream = channel.stream_stream(
        '/mediforproto.StreamingProxy/DetectStream',
        request_serializer=medifor_dot_v1_dot_streamingproxy__pb2.DetectionChunk.SerializeToString,
        response_deserializer=medifor_dot_v1_dot_streamingproxy__pb2.DetectionChunk.FromString,
        )


class StreamingProxyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DetectStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StreamingProxyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DetectStream': grpc.stream_stream_rpc_method_handler(
          servicer.DetectStream,
          request_deserializer=medifor_dot_v1_dot_streamingproxy__pb2.DetectionChunk.FromString,
          response_serializer=medifor_dot_v1_dot_streamingproxy__pb2.DetectionChunk.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mediforproto.StreamingProxy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
