# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medifor/v1/task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from medifor.v1 import analytic_pb2 as medifor_dot_v1_dot_analytic__pb2
from medifor.v1 import fusion_pb2 as medifor_dot_v1_dot_fusion__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='medifor/v1/task.proto',
  package='mediforproto',
  syntax='proto3',
  serialized_options=_b('Z2github.com/mediaforensics/medifor/pkg/mediforproto'),
  serialized_pb=_b('\n\x15medifor/v1/task.proto\x12\x0cmediforproto\x1a\x19medifor/v1/analytic.proto\x1a\x17medifor/v1/fusion.proto\"\xd3\x03\n\rDetectionTask\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x61nalytic_id\x18\x02 \x03(\t\x12\x10\n\x08\x66user_id\x18\t \x03(\t\x12*\n\tdetection\x18\x03 \x01(\x0b\x32\x17.mediforproto.Detection\x12\x12\n\ndone_queue\x18\x04 \x01(\t\x12\x33\n\x04tags\x18\x05 \x03(\x0b\x32%.mediforproto.DetectionTask.TagsEntry\x12<\n\tuser_tags\x18\x07 \x03(\x0b\x32).mediforproto.DetectionTask.UserTagsEntry\x12\x33\n\x04meta\x18\x08 \x03(\x0b\x32%.mediforproto.DetectionTask.MetaEntry\x12\x1c\n\x14\x61nalytic_timeout_sec\x18\x06 \x01(\x03\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rUserTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xfe\x01\n\nFusionTask\x12\x11\n\tunused_id\x18\x01 \x01(\t\x12\x10\n\x08\x66user_id\x18\x02 \x03(\t\x12$\n\x06\x66usion\x18\x03 \x01(\x0b\x32\x14.mediforproto.Fusion\x12\x12\n\ndone_queue\x18\x04 \x01(\t\x12\x30\n\x04tags\x18\x05 \x03(\x0b\x32\".mediforproto.FusionTask.TagsEntry\x12\x1c\n\x14\x61nalytic_timeout_sec\x18\x06 \x01(\x03\x12\x14\n\x0c\x64\x65tection_id\x18\x07 \x01(\t\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x34Z2github.com/mediaforensics/medifor/pkg/mediforprotob\x06proto3')
  ,
  dependencies=[medifor_dot_v1_dot_analytic__pb2.DESCRIPTOR,medifor_dot_v1_dot_fusion__pb2.DESCRIPTOR,])




_DETECTIONTASK_TAGSENTRY = _descriptor.Descriptor(
  name='TagsEntry',
  full_name='mediforproto.DetectionTask.TagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mediforproto.DetectionTask.TagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mediforproto.DetectionTask.TagsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=465,
)

_DETECTIONTASK_USERTAGSENTRY = _descriptor.Descriptor(
  name='UserTagsEntry',
  full_name='mediforproto.DetectionTask.UserTagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mediforproto.DetectionTask.UserTagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mediforproto.DetectionTask.UserTagsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=514,
)

_DETECTIONTASK_METAENTRY = _descriptor.Descriptor(
  name='MetaEntry',
  full_name='mediforproto.DetectionTask.MetaEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mediforproto.DetectionTask.MetaEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mediforproto.DetectionTask.MetaEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=559,
)

_DETECTIONTASK = _descriptor.Descriptor(
  name='DetectionTask',
  full_name='mediforproto.DetectionTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mediforproto.DetectionTask.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analytic_id', full_name='mediforproto.DetectionTask.analytic_id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuser_id', full_name='mediforproto.DetectionTask.fuser_id', index=2,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection', full_name='mediforproto.DetectionTask.detection', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done_queue', full_name='mediforproto.DetectionTask.done_queue', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='mediforproto.DetectionTask.tags', index=5,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_tags', full_name='mediforproto.DetectionTask.user_tags', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='mediforproto.DetectionTask.meta', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analytic_timeout_sec', full_name='mediforproto.DetectionTask.analytic_timeout_sec', index=8,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DETECTIONTASK_TAGSENTRY, _DETECTIONTASK_USERTAGSENTRY, _DETECTIONTASK_METAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=559,
)


_FUSIONTASK_TAGSENTRY = _descriptor.Descriptor(
  name='TagsEntry',
  full_name='mediforproto.FusionTask.TagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mediforproto.FusionTask.TagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mediforproto.FusionTask.TagsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=465,
)

_FUSIONTASK = _descriptor.Descriptor(
  name='FusionTask',
  full_name='mediforproto.FusionTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unused_id', full_name='mediforproto.FusionTask.unused_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuser_id', full_name='mediforproto.FusionTask.fuser_id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fusion', full_name='mediforproto.FusionTask.fusion', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done_queue', full_name='mediforproto.FusionTask.done_queue', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='mediforproto.FusionTask.tags', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analytic_timeout_sec', full_name='mediforproto.FusionTask.analytic_timeout_sec', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection_id', full_name='mediforproto.FusionTask.detection_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FUSIONTASK_TAGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=816,
)

_DETECTIONTASK_TAGSENTRY.containing_type = _DETECTIONTASK
_DETECTIONTASK_USERTAGSENTRY.containing_type = _DETECTIONTASK
_DETECTIONTASK_METAENTRY.containing_type = _DETECTIONTASK
_DETECTIONTASK.fields_by_name['detection'].message_type = medifor_dot_v1_dot_analytic__pb2._DETECTION
_DETECTIONTASK.fields_by_name['tags'].message_type = _DETECTIONTASK_TAGSENTRY
_DETECTIONTASK.fields_by_name['user_tags'].message_type = _DETECTIONTASK_USERTAGSENTRY
_DETECTIONTASK.fields_by_name['meta'].message_type = _DETECTIONTASK_METAENTRY
_FUSIONTASK_TAGSENTRY.containing_type = _FUSIONTASK
_FUSIONTASK.fields_by_name['fusion'].message_type = medifor_dot_v1_dot_fusion__pb2._FUSION
_FUSIONTASK.fields_by_name['tags'].message_type = _FUSIONTASK_TAGSENTRY
DESCRIPTOR.message_types_by_name['DetectionTask'] = _DETECTIONTASK
DESCRIPTOR.message_types_by_name['FusionTask'] = _FUSIONTASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectionTask = _reflection.GeneratedProtocolMessageType('DetectionTask', (_message.Message,), dict(

  TagsEntry = _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DETECTIONTASK_TAGSENTRY,
    __module__ = 'medifor.v1.task_pb2'
    # @@protoc_insertion_point(class_scope:mediforproto.DetectionTask.TagsEntry)
    ))
  ,

  UserTagsEntry = _reflection.GeneratedProtocolMessageType('UserTagsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DETECTIONTASK_USERTAGSENTRY,
    __module__ = 'medifor.v1.task_pb2'
    # @@protoc_insertion_point(class_scope:mediforproto.DetectionTask.UserTagsEntry)
    ))
  ,

  MetaEntry = _reflection.GeneratedProtocolMessageType('MetaEntry', (_message.Message,), dict(
    DESCRIPTOR = _DETECTIONTASK_METAENTRY,
    __module__ = 'medifor.v1.task_pb2'
    # @@protoc_insertion_point(class_scope:mediforproto.DetectionTask.MetaEntry)
    ))
  ,
  DESCRIPTOR = _DETECTIONTASK,
  __module__ = 'medifor.v1.task_pb2'
  # @@protoc_insertion_point(class_scope:mediforproto.DetectionTask)
  ))
_sym_db.RegisterMessage(DetectionTask)
_sym_db.RegisterMessage(DetectionTask.TagsEntry)
_sym_db.RegisterMessage(DetectionTask.UserTagsEntry)
_sym_db.RegisterMessage(DetectionTask.MetaEntry)

FusionTask = _reflection.GeneratedProtocolMessageType('FusionTask', (_message.Message,), dict(

  TagsEntry = _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), dict(
    DESCRIPTOR = _FUSIONTASK_TAGSENTRY,
    __module__ = 'medifor.v1.task_pb2'
    # @@protoc_insertion_point(class_scope:mediforproto.FusionTask.TagsEntry)
    ))
  ,
  DESCRIPTOR = _FUSIONTASK,
  __module__ = 'medifor.v1.task_pb2'
  # @@protoc_insertion_point(class_scope:mediforproto.FusionTask)
  ))
_sym_db.RegisterMessage(FusionTask)
_sym_db.RegisterMessage(FusionTask.TagsEntry)


DESCRIPTOR._options = None
_DETECTIONTASK_TAGSENTRY._options = None
_DETECTIONTASK_USERTAGSENTRY._options = None
_DETECTIONTASK_METAENTRY._options = None
_FUSIONTASK_TAGSENTRY._options = None
# @@protoc_insertion_point(module_scope)
